name: Deploy Blog

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: install yarn
              run: npm install yarn -g
            - run: yarn install
            - run: yarn build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./.vitepress/dist
                  cname: ibert.me

            - name: Discord
              uses: sebastianpopp/discord-action@releases/v2
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  message: Herbert He's Blog has been successfullly updated, see https://ibert.me to get more. And you can also subscribe RSS Feed at https://ibert.me/feed.xml
